version: '3'
services:
  ingestion:
    build:
      context: ./ingestion
      dockerfile: Dockerfile
    depends_on:
      - db
    links:
      - db
    volumes:
      - ${INGESTION_OBJECT_STORE_PATH}:/usr/src/app/object_store
    secrets:
      - api_key

  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgressql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  analytics:
    build:
      context: ./analytics
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      ingestion:
        condition: service_completed_successfully # Starting the analytics service once the ingestion completes

    volumes:
      - ./analytics/output:/usr/src/app/output/
      - ./db:/usr/src/app/db  # Mounting db directory for SQL file access
        
volumes:
  db:
    driver: local

secrets:
  api_key:
    file: ./api_key.txt